### PR TITLE
Add a mode for EEC to void all enchanted and damaged outputs

### PR DESCRIPTION
**Pull request by HoleFish**
So that they can be stacked in ae/infinity chest/etc.

### CODE REVIEW

**Review by kuba6000 — CHANGES_REQUESTED** [review]
That is just buff to the drops. If at all, it should be implemented as "void all damaged items" like you would do with filtered storage bus.

**Comment by HoleFish** [comment]
How should the void mode handle enchanted items? Should it void them or just "disenchant" them?

**Comment by divine-ray** [comment]
does the EEC produce liquid xp? 
I imagine it'd be possible to have it produce lxp in quantities relative to the enchantments removed.

**Comment by HoleFish** [comment]
In fact, in this pr I have already reduced the liquid xp output to 1/10 when this mode is activated, as if it were applying Mending (not exists in 1.7.10) to the drops. However, kuba apparently still thinks that this is a powerful buff

**Comment by EnderProyects** [comment]
I know it would be a huge change, but you could make that if you insert books it will output enchanted books at a rate of 1/3 being the other 2/3 full repaired tools and armour, but output 0 XP

**Comment by AbdielKavash** [comment]
The EEC should be a mob farm, not an enchanter/disenchanter/repairer/etc. If the player wants any of these functions, they can add a specialized device.

**Review by kuba6000 — APPROVED** [review]

**Pull request merged**
