### PR TITLE
Chaos recipes

### PR DESCRIPTION
**Pull request by EnderProyects**
-Added 2 chaos shards recipe, one costly but that can be done without tier 5 coils, and one "eassy" but with tier 5 coils, the use are basically for people that want many chaos shards and whant to invest in chaotic coils, and for people who are doing special runs, and can´t kill the chaos dragon

At the moment the 2 recipes work fine, but I think the voltage tier should be tweaked ( for example so the players that are doing the expert recipe for the special run can only craft it if they want the shards for stargate and have to use the maximum tier)

image

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14945

### CODE REVIEW

**Comment by Quetz4l** [comment]
If I have the choice of flying 100,000 blocks or crafting this, I'll fly..... With one dragon 20 large shards looks a lot better.

**Comment by EnderProyects** [comment]
> If I have the choice of flying 100,000 blocks or crafting this, I'll fly..... With one dragon 20 large shards looks a lot better.

the recipe is for special runs that can´t get this shards, so yes the objective is that you want to kill the chaos dragon more than doing it

**Comment by EnderProyects** [comment]
Also all the items are eassy obtainable at the endgame, being the catalyst ( not consumable) the hardest to get, but you only need them to be crafted once

**Comment by dahgul333** [comment]
too annoying recipe , better to score stuff with chaos crystals than to mine them ....
these recipes don't make things better.
something like a ton of dragonblade specialstime and transcendent would be better.

**Comment by zgggz** [comment]
too much easy

**Comment by EnderProyects** [comment]
I love how people just see the pictures, ignores the text and just complains about the recipe

> too annoying recipe , better to score stuff with chaos crystals than to mine them .... these recipes don't make things better. something like a ton of dragonblade specialstime and transcendent would be better.

**Review by kuba6000 — CHANGES_REQUESTED** [review]
I think the second recipe should be completely removed, it allows to skip the chaos dragon fight and we don't support special run cases in the pack.
As for the first recipe, there is a lot of random items it seems (maybe they should be more ender themed), if we are going to add it, it will need to be balance tested.

**Comment by EnderProyects** [comment]
About the recipe, it needs to be made 16402 times so you get the same amount of shards you would get using the inf pickaxe, I don´t think nobody in his sane mind would make that. And also, the voltage tier could be incremented to the current max one, so it can´t be crafted by any kind at early

**Comment by Dream-Master** [comment]
we can keep the first recipe if it make sense and is tested about balanced but the second recipes not.

**Comment by EnderProyects** [comment]
> we can keep the first recipe if it make sense and is tested about balanced but the second recipes not.

And... if the second recipe has a change like this one? also I changed the food in both recipes for something more interesting and end themed.
image

**Comment by kuba6000** [comment]
> > we can keep the first recipe if it make sense and is tested about balanced but the second recipes not.
> 
> And... if the second recipe has a change like this one? also I changed the food in both recipes for something more interesting and end themed. image

The recipe still allows chaos dragon skip and as I said, we do not support special recipes for special runs in the pack.
So please delete the second recipe.

**Comment by Alastors** [comment]
> > > we can keep the first recipe if it make sense and is tested about balanced but the second recipes not.
> > 
> > 
> > And... if the second recipe has a change like this one? also I changed the food in both recipes for something more interesting and end themed. image
> 
> The recipe still allows chaos dragon skip and as I said, we do not support special recipes for special runs in the pack. So please delete the second recipe.

this is absolutely untrue, we have multiple recipes for specific runs, for example skystone from obsidian, and besides who cares as long as the recipe is hard enough that it doesn't make sense in normal runs it's fine

**Comment by EnderProyects** [comment]
> > > we can keep the first recipe if it make sense and is tested about balanced but the second recipes not.
> > 
> > 
> > And... if the second recipe has a change like this one? also I changed the food in both recipes for something more interesting and end themed. image
> 
> The recipe still allows chaos dragon skip and as I said, we do not support special recipes for special runs in the pack. So please delete the second recipe.

Just saying since there is a tier 1 laputa shard, I dont think nobody is going to fight gaia almost 200 times ( using the sword of the cosmos) just to skip the dragon and get the shards needed to get the stargate, at a tier where you can just go to the island, ignore the dragon, mine the sahrds and go away with them ( also that it needs the last energy tier, and an absurd amount in total of magnetohydrodynamically constrained star matter)

**Comment by EnderProyects** [comment]
At least I pr the code, ( I could comment the second recipe in the code so it can be eassy added if is aprobed) 
P.d sorry for my english, today is not my day, and I think I made some spell failures

**Comment by EnderProyects** [comment]
@kuba6000 

Can you check at all this again and at the same time see the tiers in which everything is gated? This item is the only one that would be missing to be able to complete gog that I know of.

**Comment by EnderProyects** [comment]
It would be okay to merge if I add a config option ( off by default) that make the skip possible for the special runs? So normal players that doesn't know about the config option can't skip the fight ( btw I don't understand some devs point since ATM you can obtain the shards without killing or fighting the dragon, by just getting the shards with the inf pickaxe)

**Comment by boubou19** [comment]
This makes no sense to add at all. Intended way to get them is to kill the chaos guardian. The fact the world breaker is able to break unbreakable blocks should be fixed. There is no real point to add this aside from recipe bloat. How many people will attempt a special run with this? You and your friends? Eventually a few more persons on the discord? And how many will reach this point in the progression of the run? At this point just consider this unobtainable and cheat it in your special run.

**Pull request closed without merging**
