### PR TITLE
Update description of EEC

### PR DESCRIPTION
**Pull request by kuba6000**
Fix EEC structure tooltip issue from https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12794

### CODE REVIEW

**Comment by Dream-Master** [comment]
What if you add enchanted spikes kill quicker give more loot or enchanted ones give special loot?

**Comment by kuba6000** [comment]
> What if you add enchanted spikes kill quicker give more loot or enchanted ones give special loot?

You can insert enchanted weapon (sword) inside the ULV Input Bus

**Comment by Dream-Master** [comment]
@kuba6000 why it start to overclock at 20 ticks? isnt 1 tick international ?

**Comment by kuba6000** [comment]
> @kuba6000 why it start to overclock at 20 ticks? isnt 1 tick international ?

It overclocks normally down to 20 ticks (instead of 1) and then multiplies the outputs instead (parallel). It is done to save the tick time as the checkRecipe can take a lot of time.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
