### PR TITLE
Fix-> looting level abuse in EEC

### PR DESCRIPTION
**Pull request by Quetz4l**
Now the maximum is level 4

### CODE REVIEW

**Comment by kuba6000** [comment]
Shouldn't we fix the core of the issue (Overchanting Table trick) instead of the problems that it causes?

**Comment by LewisSaber** [comment]
> Shouldn't we fix the core of the issue (Overchanting Table trick) instead of the problems that it causes?

Why limiting game? Overenchanting takes a while to upgrade tool and takes a lot of mana, its very repetitive and boring process

**Comment by kuba6000** [comment]
> > Shouldn't we fix the core of the issue (Overchanting Table trick) instead of the problems that it causes?
> 
> Why limiting game? Overenchanting takes a while to upgrade tool and takes a lot of mana, its very repetitive and boring process
> 

If infinite enchanting is an intended feature why should we limit it here then?

**Comment by Quetz4l** [comment]
This mechanism has a more proper production increase (eu-tier). With a no-limit looting you get inbolance no matter how you look at it. Many people think the EEC with looting 4 is already too good, compared to greenhouse and other mechanisms

**Comment by Connor-Colenso** [comment]
I've heard of people getting 400k+ items/operation out of this machine because of looting abuse. This defo needs to get capped.

People having high looting is fine, using it in conjunction with automation like this is totally unbalanced.

**Review by kuba6000 — APPROVED** [review]
Ok, lets cap it then

**Pull request merged**
