### PR TITLE
Change bee render image

### PR DESCRIPTION
**Pull request by DragonStorm25**
Changes the bee image rendered on the inside of the mega apiary to a different image

Edit: The new image is inspired by https://www.reddit.com/r/PixelArt/comments/r6n3kl/minecraft_bee/, which was used as a reference image

Before
before

After
after

### CODE REVIEW

**Comment by minecraft7771** [comment]
It seems the texture is from https://www.reddit.com/r/PixelArt/comments/r6n3kl/minecraft_bee/. do you even have permission to use it here?

**Comment by DragonStorm25** [comment]
> It seems the texture is from https://www.reddit.com/r/PixelArt/comments/r6n3kl/minecraft_bee/. do you even have permission to use it here?

I did use that image as a reference, but the colors and patterns are different

**Review by kuba6000 — CHANGES_REQUESTED** [review]
I don't like it.
Looks like vanilla bee from newer versions. We are playing on 1.7.10 with forestry.
Also overall the 3D style looks weird here in my opinion.

**Comment by Dragondevi1** [comment]
This bee is much much better than current bee and should be added.

**Comment by LKD-PIX** [comment]
The original texture really needs a refactor ANYTHING is better than the first one

**Pull request closed without merging**
